---
- name: Install dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - binutils-doc
    - autoconf
    - flex
    - bison
    - libjpeg-dev
    - libfreetype6-dev
    - zlib1g-dev
    - libzmq3-dev
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - libtool
    - libffi-dev
    - curl
    - git
    - tmux
    - gettext
    - python3
    - python3-pip
    - python-dev
    - python3-dev
    - python-pip
    - virtualenvwrapper
    - libxml2-dev
    - libxslt-dev
    - nginx
    - libpq-dev
    - gunicorn

- name: Install circus
  pip: name=circus
